name: bomboskuy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/bomboskuy1.jpg
    - assets/images/logobomboskuy.jpg
    - assets/images/coklat.jpg
    - assets/images/matcha.jpg
    - assets/images/strawberry.jpg
    - assets/images/tiramisu.jpg
    - images/bomboskuy-nobg.png